language: python

python:
  - "2.7"
  
# command to install dependencies
install: 
  - pip install -r requirements.txt
  - pip install codecov
  - pip install pytest-cov

# command to run tests
script: 
  - py.test --cov=./

after_success:
  - codecov
